### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [SherylCv/prj-rev-bwfs-dasmoto#5]
Summary Grade: Satisfactory

Good job! Your files are organized nicely, and you did a great job of following the client specification -- this is an important skill to have as a developer and you seem to understand that. Moreover, you generally followed good code practice, so make sure to keep that up!

I have made some comments in your code to take note of. First off, make sure to comment the main parts of your code (both your HTML and CSS) in future projects. This will greatly help your development flow, especially as your projects get larger and more complex. Here is a quick refresher on commenting in HTML and CSS, respectively:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/31033831-917ebc5c-a52f-11e7-8c7d-877991e1a814.png">

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/31033834-92c7c4aa-a52f-11e7-8d9e-d0467d12c4e2.png">

Next off, rather than giving your brushes, frames and paint elements classes, you should instead assign them ID's since they are unique, individual elements. You usually use class when you want to give a group of elements the same styling. Here is a great resource that explains the difference between class and ID:

https://css-tricks.com/the-difference-between-id-and-class/

Good job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs).

**Comment by SherylCv** [comment]
Thank you for your review.  I am a retired RPG programmer so indenting is just part of coding for me.  I wasn't sure on the class vs id for the brush, frames and paint elements.  The article you attached really helped clarify it and drove home the fact that I need to make sure I understand this for JavaScript.  

Also, being a retired programmer, I often worked with no specs.  I was always envious of programmers who worked somewhere where specs were part of the project plan and, when I did get them, I tried to follow them as closely as possible.  Once the project is finished according to the specs, there is always room for improvement or changes based on what the user needs to do.  

As for my lack of documentation, I guess I thought that with the simple code that this was, none would be necessary.  I've always found that over-documented code was harder to read, especially as changes were made and the documentation not updated.

Again, thank you for your review.

Sheryl
